use crate::nineteen::PacketHeader;

pub enum Controller {
    AI,
    Human,
}

pub enum Driver {
    CarlosSainz = 0,
    DaniilKvyat = 1,
    DanielRicciardo = 2,
    KimiRaikkonen = 6,
    LewisHamilton = 7,
    MaxVerstappen = 9,
    NicoHulkenburg = 10,
    KevinMagnussen = 11,
    RomainGrosjean = 12,
    SebastianVettel = 13,
    SergioPerez = 14,
    ValtteriBottas = 15,
    LanceStroll = 19,
    ArronBarnes = 20,
    MartinGiles = 21,
    AlexMurray = 22,
    LucasRoth = 23,
    IgorCorreia = 24,
    SophieLevasseur = 25,
    JonasSchiffer = 26,
    AlainForest = 27,
    JayLetourneau = 28,
    EstoSaari = 29,
    YasarAtiyeh = 30,
    CallistoCalabresi = 31,
    NaotaIzum = 32,
    HowardClarke = 33,
    WilheimKaufmann = 34,
    MarieLaursen = 35,
    FlavioNieves = 36,
    PeterBelousov = 37,
    KlimekMichalski = 38,
    SantiagoMoreno = 39,
    BenjaminCoppens = 40,
    NoahVisser = 41,
    GertWaldmuller = 42,
    JulianQuesada = 43,
    DanielJones = 44,
    ArtemMarkelov = 45,
    TadasukeMakino = 46,
    SeanGelael = 47,
    NyckDeVries = 48,
    JackAitken = 49,
    GeorgeRussell = 50,
    MaximilianGunther = 51,
    NireiFukuzumi = 52,
    LucaGhiotto = 53,
    LandoNorris = 54,
    SergioSetteCamara = 55,
    LouisDeletraz = 56,
    AntonioFuoco = 57,
    CharlesLeclerc = 58,
    PierreGasly = 59,
    AlexanderAlbon = 62,
    NicholasLatifi = 63,
    DorianBoccolacci = 64,
    NikoKari = 65,
    RobertoMerhi = 66,
    ArjunMaini = 67,
    AlessioLorandi = 68,
    RubenMeijer = 69,
    RashidNair = 70,
    JackTremblay = 71,
    AntonioGiovinazzi = 74,
    RobertKubica = 75,
    NobuharuMatsushita = 78,
    NikitaMazepin = 79,
    GuanyaZhou = 80,
    MickSchumacher = 81,
    CallumIlott = 82,
    JuanManuelCorrea = 83,
    JordanKing = 84,
    MahaveerRaghunathan = 85,
    TatianaCalderon = 86,
    AnthoineHubert = 87,
    GuilianoAlesi = 88,
    RalphBoschung = 89,
}

pub enum Team {
    Mercedes = 0,
    Ferrari = 1,
    RedBullRacing = 2,
    Williams = 3,
    RacingPoint = 4,
    Renault = 5,
    ToroRosso = 6,
    Haas = 7,
    McLaren = 8,
    AlfaRomeo = 9,
    McLaren1988 = 10,
    McLaren1991 = 11,
    Williams1992 = 12,
    Ferrari1995 = 13,
    Williams1996 = 14,
    McLaren1998 = 15,
    Ferrari2002 = 16,
    Ferrari2004 = 17,
    Renault2006 = 18,
    Ferrari2007 = 19,
    RedBull2010 = 21,
    Ferrari1976 = 22,
    ARTGrandPrix = 23,
    CamposVexatecRacing = 24,
    Carlin = 25,
    CharouzRacingSystem = 26,
    DAMS = 27,
    RussianTime = 28,
    MPMotorsport = 29,
    Pertamina = 30,
    McLaren1990 = 31,
    Trident = 32,
    BWTArden = 33,
    McLaren1976 = 34,
    Lotus1972 = 35,
    Ferrari1979 = 36,
    McLaren1982 = 37,
    Williams2003 = 38,
    Brawn2009 = 39,
    Lotus1978 = 40,
    ArtGP2019 = 42,
    Campos2019 = 43,
    Carlin2019 = 44,
    SauberJuniorCharouz2019 = 45,
    Dams2019 = 46,
    UniVirtuosi2019 = 47,
    MPMotorsport2019 = 48,
    Prema2019 = 49,
    Trident2019 = 50,
    Arden2019 = 51,
    Ferrari1990 = 63,
    McLaren2010 = 64,
    Ferrari2010 = 65,
}

pub enum Nationality {
    American = 1,
    Argentinean = 2,
    Australian = 3,
    Austrian = 4,
    Azerbaijani = 5,
    Bahraini = 6,
    Belgian = 7,
    Bolivian = 8,
    Brazilian = 9,
    British = 10,
    Bulgarian = 11,
    Cameroonian = 12,
    Canadian = 13,
    Chilean = 14,
    Chinese = 15,
    Colombian = 16,
    CostaRican = 17,
    Croatian = 18,
    Cypriot = 19,
    Czech = 20,
    Danish = 21,
    Dutch = 22,
    Ecuadorian = 23,
    English = 24,
    Emirian = 25,
    Estonian = 26,
    Finnish = 27,
    French = 28,
    German = 29,
    Ghanaian = 30,
    Greek = 31,
    Guatemalan = 32,
    Honduran = 33,
    HongKonger = 34,
    Hungarian = 35,
    Icelander = 36,
    Indian = 37,
    Indonesian = 38,
    Irish = 39,
    Israeli = 40,
    Italian = 41,
    Jamaican = 42,
    Japanese = 43,
    Jordanian = 44,
    Kuwaiti = 45,
    Latvian = 46,
    Lebanese = 47,
    Lithuanian = 48,
    Luxembourger = 49,
    Malaysian = 50,
    Maltese = 51,
    Mexican = 52,
    Monegasque = 53,
    NewZealander = 54,
    Nicaraguan = 55,
    NorthKorean = 56,
    NorthernIrish = 57,
    Norwegian = 58,
    Omani = 59,
    Pakistani = 60,
    Panamanian = 61,
    Paraguayan = 62,
    Peruvian = 63,
    Polish = 64,
    Portuguese = 65,
    Qatari = 66,
    Romanian = 67,
    Russian = 68,
    Salvadoran = 69,
    Saudi = 70,
    Scottish = 71,
    Serbian = 72,
    Singaporean = 73,
    Slovakian = 74,
    Slovenian = 75,
    SouthKorean = 76,
    SouthAfrican = 77,
    Spanish = 78,
    Swedish = 79,
    Swiss = 80,
    Thai = 81,
    Turkish = 82,
    Uruguayan = 83,
    Ukrainian = 84,
    Venezuelan = 85,
    Welsh = 86,
}

/// Only the player's telemetry data is broadcast over UDP. Telemetry data of
/// other cars is restricted to prevent players gaining an unfair advantage.
pub enum UdpSetting {
    Public,
    Restricted,
}

pub struct Participant {
    /// Each car can be controlled by an AI or a human.
    controller: Controller,

    /// The driver of the car.
    driver: Driver,

    /// The team for the car.
    team: Team,

    /// The race number of the car.
    race_number: u8,

    /// The driver's nationality.
    nationality: Nationality,

    /// The driver's name. For multiplayer games, the Steam ID or LAN name is
    /// used.
    name: String,

    /// The participant's UDP setting.
    telemetry: UdpSetting,
}

pub struct ParticipantsPacket {
    /// Each packet starts with a packet header.
    pub header: PacketHeader,

    /// A list of participants in the race.
    pub participants: Vec<Participant>,
}
